### PR TITLE
Update versioneer.py to 0.29

### PR DESCRIPTION
**Pull request by davidzchen**
Generated using:

```
versioneer install --vendor
```

Bug: #33

This change is [Reviewable](https://reviewable.io/reviews/zeldamods/oead/35)

### CODE REVIEW

**Comment by davidzchen** [comment]
I wasn't able to test this though. When I ran `python3 setup.py bdist_wheel`, I got the following error regarding `pybyind11_add_module`:

```
python3 setup.py bdist_wheel
running bdist_wheel
running build
running build_ext
CMake Error at CMakeLists.txt:31 (add_subdirectory):
  The source directory

    /Users/dzc/Projects/davidzchen/forks/oead/lib/pybind11

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:33 (pybind11_add_module):
  Unknown CMake command "pybind11_add_module".


-- Configuring incomplete, errors occurred!
Traceback (most recent call last):
  File "/Users/dzc/Projects/davidzchen/forks/oead/setup.py", line 64, in <module>
    setuptools.setup(
  File "/opt/homebrew/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 184, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
    dist.run_commands()
  File "/opt/homebrew/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/opt/homebrew/lib/python3.12/site-packages/setuptools/dist.py", line 968, in run_command
    super().run_command(command)
  File "/opt/homebrew/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/opt/homebrew/lib/python3.12/site-packages/wheel/bdist_wheel.py", line 368, in run
    self.run_command("build")
  File "/opt/homebrew/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/opt/homebrew/lib/python3.12/site-packages/setuptools/dist.py", line 968, in run_command
    super().run_command(command)
  File "/opt/homebrew/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/opt/homebrew/lib/python3.12/site-packages/setuptools/_distutils/command/build.py", line 132, in run
    self.run_command(cmd_name)
  File "/opt/homebrew/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/opt/homebrew/lib/python3.12/site-packages/setuptools/dist.py", line 968, in run_command
    super().run_command(command)
  File "/opt/homebrew/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/Users/dzc/Projects/davidzchen/forks/oead/setup.py", line 29, in run
    self.build_extension(ext)
  File "/Users/dzc/Projects/davidzchen/forks/oead/setup.py", line 54, in build_extension
    subprocess.check_call([cmake_name, ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/Users/dzc/Projects/davidzchen/forks/oead/py', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/dzc/Projects/davidzchen/forks/oead/build/lib.macosx-14.0-arm64-cpython-312', '-DPYTHON_EXECUTABLE=/opt/homebrew/opt/python@3.12/bin/python3.12', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
```

**Comment by davidzchen** [comment]
I thought that it was because I didn't have `pybind11` installed. I tried installing it with both `pipx install pybind11` and `brew install pybind11` but am still getting the same error.

I am on macOS Sonoma 14.4.1.

```
$ which cmake
/opt/homebrew/bin/cmake
$ cmake --version
cmake version 3.29.5

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

Do you have any pointers on how to resolve this error?

**Comment by davidzchen** [comment]
Here is the full error I get when run `pipx install -e .`:

```
$ pipx install -e .
  error: subprocess-exited-with-error

  × Building editable for oead (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [135 lines of output]
      running editable_wheel                                                                                                                                                                                                                                                                                                                                                                               19:28:34 [0/85]
      creating /private/var/folders/d3/yj9wzlg96ql05cjzm329d76r0000gn/T/pip-wheel-7xqayvcb/.tmp-h9o5xsol/oead.egg-info
      writing /private/var/folders/d3/yj9wzlg96ql05cjzm329d76r0000gn/T/pip-wheel-7xqayvcb/.tmp-h9o5xsol/oead.egg-info/PKG-INFO
      writing dependency_links to /private/var/folders/d3/yj9wzlg96ql05cjzm329d76r0000gn/T/pip-wheel-7xqayvcb/.tmp-h9o5xsol/oead.egg-info/dependency_links.txt
      writing top-level names to /private/var/folders/d3/yj9wzlg96ql05cjzm329d76r0000gn/T/pip-wheel-7xqayvcb/.tmp-h9o5xsol/oead.egg-info/top_level.txt
      writing manifest file '/private/var/folders/d3/yj9wzlg96ql05cjzm329d76r0000gn/T/pip-wheel-7xqayvcb/.tmp-h9o5xsol/oead.egg-info/SOURCES.txt'
      reading manifest file '/private/var/folders/d3/yj9wzlg96ql05cjzm329d76r0000gn/T/pip-wheel-7xqayvcb/.tmp-h9o5xsol/oead.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE.md'
      writing manifest file '/private/var/folders/d3/yj9wzlg96ql05cjzm329d76r0000gn/T/pip-wheel-7xqayvcb/.tmp-h9o5xsol/oead.egg-info/SOURCES.txt'
      creating '/private/var/folders/d3/yj9wzlg96ql05cjzm329d76r0000gn/T/pip-wheel-7xqayvcb/.tmp-h9o5xsol/oead-0+untagged.159.g3b3bef0.dist-info'
      creating /private/var/folders/d3/yj9wzlg96ql05cjzm329d76r0000gn/T/pip-wheel-7xqayvcb/.tmp-h9o5xsol/oead-0+untagged.159.g3b3bef0.dist-info/WHEEL
      running build_ext
      -- The CXX compiler identification is AppleClang 15.0.0.15000309
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      CMake Error at CMakeLists.txt:31 (add_subdirectory):
        The source directory

          /Users/dzc/Projects/davidzchen/forks/oead/lib/pybind11

        does not contain a CMakeLists.txt file.


      CMake Error at CMakeLists.txt:33 (pybind11_add_module):
        Unknown CMake command "pybind11_add_module".


      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "/private/var/folders/d3/yj9wzlg96ql05cjzm329d76r0000gn/T/pip-build-env-vhamdodh/overlay/lib/python3.12/site-packages/setuptools/command/editable_wheel.py", line 155, in run
          self._create_wheel_file(bdist_wheel)
        File "/private/var/folders/d3/yj9wzlg96ql05cjzm329d76r0000gn/T/pip-build-env-vhamdodh/overlay/lib/python3.12/site-packages/setuptools/command/editable_wheel.py", line 357, in _create_wheel_file
          files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/d3/yj9wzlg96ql05cjzm329d76r0000gn/T/pip-build-env-vhamdodh/overlay/lib/python3.12/site-packages/setuptools/command/editable_wheel.py", line 280, in _run_build_commands
          self._run_build_subcommands()
        File "/private/var/folders/d3/yj9wzlg96ql05cjzm329d76r0000gn/T/pip-build-env-vhamdodh/overlay/lib/python3.12/site-packages/setuptools/command/editable_wheel.py", line 307, in _run_build_subcommands
          self.run_command(name)
        File "/private/var/folders/d3/yj9wzlg96ql05cjzm329d76r0000gn/T/pip-build-env-vhamdodh/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/d3/yj9wzlg96ql05cjzm329d76r0000gn/T/pip-build-env-vhamdodh/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 968, in run_command
          super().run_command(command)
        File "/private/var/folders/d3/yj9wzlg96ql05cjzm329d76r0000gn/T/pip-build-env-vhamdodh/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 29, in run
        File "<string>", line 54, in build_extension
        File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/Users/dzc/Projects/davidzchen/forks/oead/py', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/dzc/Projects/davidzchen/forks/oead', '-DPYTHON_EXECUTABLE=/private/var/folders/d3/yj9wzlg96ql05cjzm329d76r0000gn/T/tmpif_msdjo/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
      /private/var/folders/d3/yj9wzlg96ql05cjzm329d76r0000gn/T/pip-build-env-vhamdodh/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py:988: _DebuggingTips: Problem in editable installation.
      !!

              ********************************************************************************
              An error happened while installing `oead` in editable mode.

              The following steps are recommended to help debug this problem:

              - Try to install the project normally, without using the editable mode.
                Does the error still persist?
                (If it does, try fixing the problem before attempting the editable mode).
              - If you are using binary extensions, make sure you have all OS-level
                dependencies installed (e.g. compilers, toolchains, binary libraries, ...).
              - Try the latest version of setuptools (maybe the error was already fixed).
              - If you (or your project dependencies) are using any setuptools extension
                or customization, make sure they support the editable mode.

              After following the steps above, if the problem still persists and
              you think this is related to how setuptools handles editable installations,
              please submit a reproducible example
              (see https://stackoverflow.com/help/minimal-reproducible-example) to:

                  https://github.com/pypa/setuptools/issues

              See https://setuptools.pypa.io/en/latest/userguide/development_mode.html for details.
              ********************************************************************************

      !!
        cmd_obj.run()
      Traceback (most recent call last):
        File "/Users/dzc/.local/pipx/shared/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/dzc/.local/pipx/shared/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/dzc/.local/pipx/shared/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 273, in build_editable
          return hook(wheel_directory, config_settings, metadata_directory)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/d3/yj9wzlg96ql05cjzm329d76r0000gn/T/pip-build-env-vhamdodh/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 443, in build_editable
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/d3/yj9wzlg96ql05cjzm329d76r0000gn/T/pip-build-env-vhamdodh/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 395, in _build_with_temp_dir
          self.run_setup()
        File "/private/var/folders/d3/yj9wzlg96ql05cjzm329d76r0000gn/T/pip-build-env-vhamdodh/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/d3/yj9wzlg96ql05cjzm329d76r0000gn/T/pip-build-env-vhamdodh/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 64, in <module>
        File "/private/var/folders/d3/yj9wzlg96ql05cjzm329d76r0000gn/T/pip-build-env-vhamdodh/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/d3/yj9wzlg96ql05cjzm329d76r0000gn/T/pip-build-env-vhamdodh/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/d3/yj9wzlg96ql05cjzm329d76r0000gn/T/pip-build-env-vhamdodh/overlay/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/private/var/folders/d3/yj9wzlg96ql05cjzm329d76r0000gn/T/pip-build-env-vhamdodh/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/d3/yj9wzlg96ql05cjzm329d76r0000gn/T/pip-build-env-vhamdodh/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 968, in run_command
          super().run_command(command)
        File "/private/var/folders/d3/yj9wzlg96ql05cjzm329d76r0000gn/T/pip-build-env-vhamdodh/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/d3/yj9wzlg96ql05cjzm329d76r0000gn/T/pip-build-env-vhamdodh/overlay/lib/python3.12/site-packages/setuptools/command/editable_wheel.py", line 155, in run
          self._create_wheel_file(bdist_wheel)
        File "/private/var/folders/d3/yj9wzlg96ql05cjzm329d76r0000gn/T/pip-build-env-vhamdodh/overlay/lib/python3.12/site-packages/setuptools/command/editable_wheel.py", line 357, in _create_wheel_file
          files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/d3/yj9wzlg96ql05cjzm329d76r0000gn/T/pip-build-env-vhamdodh/overlay/lib/python3.12/site-packages/setuptools/command/editable_wheel.py", line 280, in _run_build_commands
          self._run_build_subcommands()
        File "/private/var/folders/d3/yj9wzlg96ql05cjzm329d76r0000gn/T/pip-build-env-vhamdodh/overlay/lib/python3.12/site-packages/setuptools/command/editable_wheel.py", line 307, in _run_build_subcommands
          self.run_command(name)
        File "/private/var/folders/d3/yj9wzlg96ql05cjzm329d76r0000gn/T/pip-build-env-vhamdodh/overlay/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/private/var/folders/d3/yj9wzlg96ql05cjzm329d76r0000gn/T/pip-build-env-vhamdodh/overlay/lib/python3.12/site-packages/setuptools/dist.py", line 968, in run_command
          super().run_command(command)
        File "/private/var/folders/d3/yj9wzlg96ql05cjzm329d76r0000gn/T/pip-build-env-vhamdodh/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 29, in run
        File "<string>", line 54, in build_extension
        File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/Users/dzc/Projects/davidzchen/forks/oead/py', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/dzc/Projects/davidzchen/forks/oead', '-DPYTHON_EXECUTABLE=/private/var/folders/d3/yj9wzlg96ql05cjzm329d76r0000gn/T/tmpif_msdjo/bin/python', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building editable for oead
ERROR: Could not build wheels for oead, which is required to install pyproject.toml-based projects
Cannot determine package name from spec '/Users/dzc/Projects/davidzchen/forks/oead'. Check package spec for errors.
```

It seems to be complaining about the same error.

**Comment by leoetlino** [comment]
Did you remember to fetch the submodules?

**Comment by davidzchen** [comment]
Sorry, forgot I had to do that.

**Comment by davidzchen** [comment]
Now I am getting a different CMake error (`Unknown CMake command "c4_declare_project".`):

```
$ python3 setup.py bdist_wheel
running bdist_wheel
running build
running build_ext
CMake Deprecation Warning at /Users/dzc/Projects/davidzchen/forks/oead/lib/pybind11/CMakeLists.txt:8 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- pybind11 v2.10.1
CMake Warning (dev) at /Users/dzc/Projects/davidzchen/forks/oead/lib/pybind11/tools/FindPythonLibsNew.cmake:98 (find_package):
  Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
  are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

Call Stack (most recent call first):
  /Users/dzc/Projects/davidzchen/forks/oead/lib/pybind11/tools/pybind11Tools.cmake:50 (find_package)
  /Users/dzc/Projects/davidzchen/forks/oead/lib/pybind11/tools/pybind11Common.cmake:180 (include)
  /Users/dzc/Projects/davidzchen/forks/oead/lib/pybind11/CMakeLists.txt:206 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found PythonInterp: /opt/homebrew/opt/python@3.12/bin/python3.12 (found suitable version "3.12.4", minimum required is "3.6")
-- Found PythonLibs: /opt/homebrew/opt/python@3.12/Frameworks/Python.framework/Versions/3.12/lib/libpython3.12.dylib
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- Performing Test HAS_FLTO_THIN
-- Performing Test HAS_FLTO_THIN - Success
CMake Deprecation Warning at /Users/dzc/Projects/davidzchen/forks/oead/CMakeRC.cmake:37 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
Call Stack (most recent call first):
  /Users/dzc/Projects/davidzchen/forks/oead/CMakeLists.txt:16 (include)


CMake Warning at /Users/dzc/Projects/davidzchen/forks/oead/lib/abseil/CMakeLists.txt:72 (message):
  A future Abseil release will default ABSL_PROPAGATE_CXX_STD to ON for CMake
  3.8 and up.  We recommend enabling this option to ensure your project still
  builds correctly.


-- Performing Test ABSL_INTERNAL_AT_LEAST_CXX17
-- Performing Test ABSL_INTERNAL_AT_LEAST_CXX17 - Success
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE
CMake Deprecation Warning at /Users/dzc/Projects/davidzchen/forks/oead/lib/libyaml/CMakeLists.txt:2 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The C compiler identification is AppleClang 15.0.0.15000309
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features                                                                                                                                                                                                                                                                           -- Detecting C compile features - done
CMake Warning (dev) at /opt/homebrew/Cellar/cmake/3.29.5/share/cmake/Modules/CTest.cmake:50 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'BUILD_TESTING'.
Call Stack (most recent call first):
  /Users/dzc/Projects/davidzchen/forks/oead/lib/libyaml/CMakeLists.txt:101 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Deprecation Warning at /Users/dzc/Projects/davidzchen/forks/oead/lib/ordered-map/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Error at /Users/dzc/Projects/davidzchen/forks/oead/lib/rapidyaml/CMakeLists.txt:4 (include):
  include could not find requested file:

    ./ext/c4core/cmake/c4Project.cmake


CMake Error at /Users/dzc/Projects/davidzchen/forks/oead/lib/rapidyaml/CMakeLists.txt:6 (c4_declare_project):
  Unknown CMake command "c4_declare_project".


-- Configuring incomplete, errors occurred!
Traceback (most recent call last):
  File "/Users/dzc/Projects/davidzchen/forks/oead/setup.py", line 64, in <module>
    setuptools.setup(
  File "/opt/homebrew/lib/python3.12/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 184, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
    dist.run_commands()
  File "/opt/homebrew/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/opt/homebrew/lib/python3.12/site-packages/setuptools/dist.py", line 968, in run_command
    super().run_command(command)
  File "/opt/homebrew/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/opt/homebrew/lib/python3.12/site-packages/wheel/bdist_wheel.py", line 368, in run
    self.run_command("build")
  File "/opt/homebrew/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/opt/homebrew/lib/python3.12/site-packages/setuptools/dist.py", line 968, in run_command
    super().run_command(command)
  File "/opt/homebrew/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/opt/homebrew/lib/python3.12/site-packages/setuptools/_distutils/command/build.py", line 132, in run
    self.run_command(cmd_name)
  File "/opt/homebrew/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "/opt/homebrew/lib/python3.12/site-packages/setuptools/dist.py", line 968, in run_command
    super().run_command(command)
  File "/opt/homebrew/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/Users/dzc/Projects/davidzchen/forks/oead/setup.py", line 29, in run
    self.build_extension(ext)
  File "/Users/dzc/Projects/davidzchen/forks/oead/setup.py", line 54, in build_extension
    subprocess.check_call([cmake_name, ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/Users/dzc/Projects/davidzchen/forks/oead/py', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/dzc/Projects/davidzchen/forks/oead/build/lib.macosx-14.0-arm64-cpython-312', '-DPYTHON_EXECUTABLE=/opt/homebrew/opt/python@3.12/bin/python3.12', '-DCMAKE_BUILD
_TYPE=Release']' returned non-zero exit status 1.
```

**Comment by leoetlino** [comment]
As per the readme, you need to fetch submodules with `git submodule update --init --recursive` (the --recursive is important here)

**Comment by davidzchen** [comment]
Thanks. The build succeeded using `python3 setup.py bdist_wheel` after fetching the submodules recursively.

**Comment by davidzchen** [comment]
I was also able to successfully install the package in my Python venv:

```
$ python3 -m pip install -e .
Obtaining file:///Users/dzc/Projects/davidzchen/forks/oead
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Installing backend dependencies ... done
  Preparing editable metadata (pyproject.toml) ... done
Building wheels for collected packages: oead
  Building editable for oead (pyproject.toml) ... done
  Created wheel for oead: filename=oead-0+untagged.159.g3b3bef0-0.editable-cp312-cp312-macosx_14_0_arm64.whl size=11353 sha256=587b98c69c707481aba69b00c777f4cab393a608006427c7cfcf05c74dcf72dd
  Stored in directory: /private/var/folders/d3/yj9wzlg96ql05cjzm329d76r0000gn/T/pip-ephem-wheel-cache-cfmls3gf/wheels/b1/1b/76/0d0ef498b51a03bf8f2ba847b0e8c1b960a88030052b6e4114
Successfully built oead
Installing collected packages: oead
Successfully installed oead-0+untagged.159.g3b3bef0
```

Sorry, things have been a bit hectic here. I need to read things more carefully.

**Review by leoetlino — APPROVED** [review]
Thanks!

**Pull request merged**
